export const cards: any = [ 
    {cardName: "assets/cards/aceOfClubs.png", cardValue: 1},
    {cardName: "assets/cards/aceOfDiamonds.png", cardValue: 1},
    {cardName: "assets/cards/aceOfHearts.png", cardValue:  1 },
    {cardName: "assets/cards/aceOfSpades.png", cardValue: 1},
    {cardName: "assets/cards/eightOfClubs.png", cardValue: 8 },
    {cardName: "assets/cards/eightOfDiamonds.png", cardValue: 8},
    {cardName: "assets/cards/eightOfHearts.png", cardValue: 8},
    {cardName: "assets/cards/eightOfSpades.png", cardValue: 8},
    {cardName: "assets/cards/fiveOfClubs.png", cardValue: 5},
    {cardName: "assets/cards/fiveOfDiamonds.png", cardValue: 5},
    {cardName: "assets/cards/fiveOfHearts.png", cardValue: 5},
    {cardName: "assets/cards/fiveOfSpades.png", cardValue: 5},
    {cardName: "assets/cards/fourOfClubs.png", cardValue: 4},
    {cardName: "assets/cards/fourOfDiamonds.png", cardValue: 4},
    {cardName: "assets/cards/fourOfHearts.png", cardValue: 4},
    {cardName: "assets/cards/fourOfSpades.png", cardValue: 4},
    {cardName: "assets/cards/jackOfClubs.png", cardValue: 10},
    {cardName: "assets/cards/jackOfDiamonds.png", cardValue: 10},
    {cardName: "assets/cards/jackOfHearts.png", cardValue: 10},
    {cardName: "assets/cards/jackOfSpades.png", cardValue: 10},
    {cardName: "assets/cards/kingOfClubs.png", cardValue: 10},
    {cardName: "assets/cards/kingOfDiamonds.png", cardValue: 10},
    {cardName: "assets/cards/kingOfHearts.png", cardValue: 10},
    {cardName: "assets/cards/kingOfSpades.png", cardValue: 10},
    {cardName: "assets/cards/nineOfClubs.png", cardValue: 9},
    {cardName: "assets/cards/nineOfDiamonds.png", cardValue: 9},
    {cardName: "assets/cards/nineOfHearts.png", cardValue: 9},
    {cardName: "assets/cards/nineOfSpades.png", cardValue: 9},
    {cardName: "assets/cards/queenOfClubs.png", cardValue: 10},
    {cardName: "assets/cards/queenOfDiamonds.png", cardValue: 10,},
    {cardName: "assets/cards/queenOfHearts.png", cardValue: 10},
    {cardName: "assets/cards/queenOfSpades.png", cardValue: 10},
    {cardName: "assets/cards/sevenOfClubs.png", cardValue: 7},
    {cardName: "assets/cards/sevenOfDiamonds.png", cardValue: 7},
    {cardName: "assets/cards/sevenOfHearts.png", cardValue: 7},
    {cardName: "assets/cards/sevenOfSpades.png", cardValue: 7},
    {cardName: "assets/cards/sixOfClubs.png", cardValue: 6},
    {cardName: "assets/cards/sixOfDiamonds.png", cardValue: 6},
    {cardName: "assets/cards/sixOfHearts.png", cardValue: 6},
    {cardName: "assets/cards/sixOfSpades.png", cardValue: 6},
    {cardName: "assets/cards/tenOfClubs.png", cardValue: 10},
    {cardName: "assets/cards/tenOfDiamonds.png", cardValue: 10},
    {cardName: "assets/cards/tenOfHearts.png", cardValue: 10},
    {cardName: "assets/cards/tenOfSpades.png", cardValue: 10},
    {cardName: "assets/cards/threeOfClubs.png", cardValue: 3},
    {cardName: "assets/cards/threeOfDiamonds.png", cardValue: 3},
    {cardName: "assets/cards/threeOfHearts.png", cardValue: 3},
    {cardName: "assets/cards/threeOfSpades.png", cardValue: 3},
    {cardName: "assets/cards/twoOfClubs.png", cardValue: 2},
    {cardName: "assets/cards/twoOfDiamonds.png", cardValue: 2},
    {cardName: "assets/cards/twoOfHearts.png", cardValue: 2},
    {cardName: "assets/cards/twoOfSpades.png", cardValue: 2}
]

export interface Card {
  cardName: string,
  cardValue: number
}